# Generated by Django 4.1.7 on 2023-04-03 01:30

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "reviewID",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("userID", models.CharField(max_length=255, null=True)),
                ("toiletID", models.CharField(max_length=255, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("comment", models.CharField(default="", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Toilet",
            fields=[
                (
                    "toiletID",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="", max_length=255, null=True)),
                ("address", models.CharField(default="", max_length=255, null=True)),
                ("postalCode", models.CharField(default="", max_length=255, null=True)),
                ("floorNumber", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "unitNumber",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=9,
                        validators=[
                            django.core.validators.MaxValueValidator(180),
                            django.core.validators.MinValueValidator(-180),
                        ],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=8,
                        validators=[
                            django.core.validators.MaxValueValidator(90),
                            django.core.validators.MinValueValidator(-90),
                        ],
                    ),
                ),
                (
                    "locationType",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("isPublic", models.BooleanField(blank=True, default=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Traffic",
            fields=[
                (
                    "trafficID",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("trafficType", models.CharField(default="", max_length=255)),
                ("message", models.CharField(default="", max_length=255)),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=9,
                        validators=[
                            django.core.validators.MaxValueValidator(180),
                            django.core.validators.MinValueValidator(-180),
                        ],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=8,
                        validators=[
                            django.core.validators.MaxValueValidator(90),
                            django.core.validators.MinValueValidator(-90),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("name", models.CharField(max_length=255, null=True)),
                ("emailAddress", models.EmailField(max_length=255, null=True)),
                ("password", models.CharField(max_length=255, null=True)),
                (
                    "userID",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("sessionID", models.CharField(max_length=255, null=True)),
                (
                    "favToilets",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
