# Generated by Django 4.1.7 on 2023-04-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("singlepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toilet",
            name="locationType",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
