# Generated by Django 3.1.4 on 2023-02-22 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0002_mop_toilet_rename_name_user_displayname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.PositiveIntegerField(default=0)),
                ('latitude', models.PositiveIntegerField(default=0)),
                ('addressLineOne', models.CharField(default='', max_length=255, null=True)),
                ('addressLineTwo', models.CharField(default='', max_length=255, null=True)),
                ('postalCode', models.PositiveIntegerField(default='000000', null=True)),
                ('floorNumber', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('comment', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mop',
            name='age',
        ),
        migrations.RemoveField(
            model_name='mop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='mop',
            name='sessionID',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='toilet',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toilet',
            name='toiletType',
            field=models.CharField(default='public', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='emailAddress',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mop',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='E7r9t8@Q#h%Hy+M', max_length=128),
        ),
    ]
