# Generated by Django 4.1.7 on 2023-04-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("singlepage", "0003_alter_toilet_floornumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
