# Generated by Django 3.1.4 on 2023-02-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0003_auto_20230222_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mop',
            name='sessionID',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
    ]
