# Generated by Django 4.1.7 on 2023-03-25 08:09

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("singlepage", "0005_remove_user_id_user_sessionid_user_userid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toilet",
            name="id",
        ),
        migrations.AddField(
            model_name="review",
            name="toiletID",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="userID",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="toilet",
            name="address",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="toilet",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=8,
                validators=[
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(-90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="toilet",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=9,
                validators=[
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                ],
            ),
        ),
        migrations.AddField(
            model_name="toilet",
            name="postalCode",
            field=models.CharField(default="None", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="toilet",
            name="toiletID",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="userID",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
