# Generated by Django 4.1.6 on 2023-03-28 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0006_remove_toilet_id_review_toiletid_review_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
