# Generated by Django 4.1.7 on 2023-03-29 08:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("singlepage", "0011_alter_user_favtoilets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favToilets",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
