# Generated by Django 4.1.7 on 2023-03-31 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("singlepage", "0015_alter_toilet_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="toilet",
            managers=[],
        ),
    ]
