# Generated by Django 4.1.6 on 2023-04-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0019_alter_toilet_ispublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='unitNumber',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
